import { FormEvent, useEffect, useMemo, useState } from "react";
import * as echarts from "echarts";
import { api } from "./api";
import { useSimulator } from "./use-simulator";

type Page = "overview" | "control" | "lab";
type Toast = { tone: "success" | "error"; text: string } | null;

const point = (values: Record<string, number>, device: string, slug: string) => values[`${device}/${slug}`] ?? 0;
const number = (value: number, digits = 1) => new Intl.NumberFormat("en-US", { maximumFractionDigits: digits, minimumFractionDigits: digits }).format(value);

function Chip({ tone = "neutral", children }: { tone?: "neutral" | "good" | "active" | "warning" | "danger" | "offline"; children: React.ReactNode }) { return <span className={`chip chip--${tone}`}><span aria-hidden="true">{tone === "warning" ? "!" : tone === "danger" ? "×" : tone === "good" ? "●" : "•"}</span>{children}</span>; }
function Card({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}><h2>{title}</h2>{children}</section>; }
function Metric({ label, value, detail, tone = "neutral" }: { label: string; value: string; detail?: string; tone?: "neutral" | "good" | "warning" | "danger" }) { return <section className={`metric metric--${tone}`}><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</section>; }
function ConfirmationDialog({ title, detail, onCancel, onConfirm }: { title: string; detail: string; onCancel: () => void; onConfirm: () => void }) { return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><p className="eyebrow">Confirmation required</p><h2 id="dialog-title">{title}</h2><p>{detail}</p><div className="button-row"><button className="button button--secondary" onClick={onCancel}>Cancel</button><button className="button button--danger" onClick={onConfirm}>Confirm action</button></div></section></div>; }

function MiniChart({ title, value, unit, tone }: { title: string; value: number; unit: string; tone: string }) {
  const id = `chart-${title.replaceAll(" ", "-")}`;
  const samples = Array.from({ length: 18 }, (_, index) => value + Math.sin(index / 2) * Math.max(Math.abs(value) * 0.035, 1));
  const ref = (node: HTMLDivElement | null) => {
    if (!node) return;
    const chart = echarts.init(node, undefined, { renderer: "svg" });
    chart.setOption({ animation: false, grid: { left: 4, right: 4, top: 10, bottom: 2 }, xAxis: { type: "category", show: false, data: samples.map(String) }, yAxis: { type: "value", show: false }, series: [{ type: "line", data: samples, smooth: true, symbol: "none", lineStyle: { width: 2, color: tone }, areaStyle: { color: `${tone}22` } }] });
  };
  return <Card title={title} className="chart-card"><div className="chart-value">{number(value)} <small>{unit}</small></div><div id={id} ref={ref} className="chart" role="img" aria-label={`${title}: current value ${number(value)} ${unit}`} /></Card>;
}

export function App() {
  const simulator = useSimulator();
  const [page, setPage] = useState<Page>("overview");
  const [toast, setToast] = useState<Toast>(null);
  const notify = (next: Toast) => { setToast(next); if (next) window.setTimeout(() => setToast(null), 5000); };
  useEffect(() => {
    if (!simulator.lastEvent) return;
    const messages: Record<string, string> = {
      reset: "Simulator reset was confirmed by the backend.",
      diagnostic: "The simulator reported an accepted-but-unsupported command.",
      scenario_step: `Scenario step ${String(simulator.lastEvent.payload.index ?? "")} completed.`,
      fault: `Fault ${String(simulator.lastEvent.payload.device ?? "")} / ${String(simulator.lastEvent.payload.slug ?? "")} changed.`
    };
    notify({ tone: simulator.lastEvent.type === "fault" ? "error" : "success", text: messages[simulator.lastEvent.type] });
  }, [simulator.lastEvent?.id]);
  const props = { ...simulator, notify };
  return <div className="app-shell">
    <header className="topbar"><div className="brand">M261 <b>SIMULATOR</b></div><nav aria-label="Console"><button className={page === "overview" ? "is-active" : ""} onClick={() => setPage("overview")}>Overview / Demo</button><button className={page === "control" ? "is-active" : ""} onClick={() => setPage("control")}>Control</button><button className={page === "lab" ? "is-active" : ""} onClick={() => setPage("lab")}>Test Lab</button></nav><div className="topbar-status"><span>{simulator.modelTime ? new Date(simulator.modelTime).toLocaleString() : "Loading time…"}</span><Chip tone={simulator.stream === "connected" ? "good" : simulator.stream === "offline" ? "offline" : "warning"}>{simulator.stream === "connected" ? "Connected" : simulator.stream === "offline" ? "Offline" : "Connecting"}</Chip></div></header>
    <main>{page === "overview" && <Overview {...props} />}{page === "control" && <Control {...props} />}{page === "lab" && <TestLab {...props} />}</main>
    {toast && <div className={`toast toast--${toast.tone}`} role="status">{toast.text}</div>}
  </div>;
}

function Overview({ points, catalog, status, modelTime, notify, lastEvent }: ReturnType<typeof useSimulator> & { notify: (toast: Toast) => void }) {
  const soc = point(points, "BMS", "soc"); const power = point(points, "EMS", "last_charge_discharge_power_kw"); const requested = point(points, "EMS", "desired_active_power_kw"); const temperature = point(points, "BMS", "average_temperature_c");
  const alarmCount = catalog.filter((item) => item.class === "alarm" && point(points, item.device, item.slug) !== 0).length;
  const prepare = async () => { try { await api.demoPrepare(); notify({ tone: "success", text: "Demo environment prepared and confirmed by the simulator." }); } catch (error) { notify({ tone: "error", text: (error as Error).message }); } };
  return <><div className="page-heading"><div><p className="eyebrow">Live simulator view</p><h1>Overview / Demo</h1><p>Current state from the simulator backend.</p></div><button className="button button--primary" onClick={() => void prepare()}>Prepare Demo</button></div>
    <div className="metric-grid"><Metric label="State of charge" value={`${number(soc)} %`} detail="BMS source" tone="good" /><Metric label={power < 0 ? "Charging" : power > 0 ? "Discharging" : "Idle"} value={`${number(Math.abs(power))} kW`} detail="Actual power" tone={power === 0 ? "neutral" : "good"} /><Metric label="Requested power" value={`${number(requested)} kW`} detail="Minus = charge" /><Metric label="Active alarms" value={String(alarmCount)} detail="No inferred severity" tone={alarmCount ? "danger" : "good"} /></div>
    {lastEvent?.type === "fault" && Number(lastEvent.payload.value) !== 0 && <div className="event-banner" role="alert"><b>Alarm injected:</b> {String(lastEvent.payload.device)}/{String(lastEvent.payload.slug)}. Its physical effect is unconfirmed by the documentation.</div>}
    <div className="dashboard-grid"><MiniChart title="SoC and power" value={soc} unit="%" tone="#2367D1" /><MiniChart title="Battery temperature" value={temperature} unit="°C" tone="#A86500" /><Card title="System state"><dl className="definition-list"><dt>Mode</dt><dd>{point(points, "EMS", "set_operating_mode") === 2 ? "Remote" : "Manual / Auto"}</dd><dt>Model time</dt><dd>{modelTime ? new Date(modelTime).toLocaleString() : "Awaiting stream"}</dd><dt>Control readiness</dt><dd><Chip tone={status?.ready ? "good" : "warning"}>{status?.ready ? "Ready" : "Not ready"}</Chip></dd></dl></Card><Card title="Device summary"><div className="device-list">{["EMS", "PCS", "BMS", "PCS_METER"].map((device) => <div key={device}><span>{device}</span><Chip tone="good">Online</Chip></div>)}</div></Card></div>
    <Card title="Simulator configuration"><div className="config-list">{Object.entries(status?.configuration ?? {}).map(([key, setting]) => <div key={key}><span>{key}</span><span>{String(setting.value)}</span>{setting.unconfirmed && <Chip tone="warning">Unconfirmed</Chip>}</div>)}</div></Card></>;
}

function Control({ points, notify }: ReturnType<typeof useSimulator> & { notify: (toast: Toast) => void }) {
  const [power, setPower] = useState(String(point(points, "EMS", "set_active_power_kw"))); const [reactive, setReactive] = useState("0"); const [mode, setMode] = useState("2"); const [on, setOn] = useState("1"); const [maxChargeSOC, setMaxChargeSOC] = useState("90"); const [minDischargeSOC, setMinDischargeSOC] = useState("10"); const [maxChargePower, setMaxChargePower] = useState("100"); const [maxDischargePower, setMaxDischargePower] = useState("100"); const [pending, setPending] = useState(false); const [danger, setDanger] = useState<{ slug: string; label: string } | null>(null);
  const send = async (event: FormEvent) => { event.preventDefault(); setPending(true); try { await api.command("EMS", "power_on_off", Number(on)); await api.command("EMS", "set_operating_mode", Number(mode)); await api.command("EMS", "set_active_power_kw", Number(power)); await api.command("EMS", "set_reactive_power_kvar", Number(reactive)); await api.command("EMS", "maximum_charge_soc", Number(maxChargeSOC)); await api.command("EMS", "minimum_discharge_soc", Number(minDischargeSOC)); await api.command("EMS", "system_maximum_charge_power", Number(maxChargePower)); await api.command("EMS", "system_maximum_discharge_power", Number(maxDischargePower)); notify({ tone: "success", text: "Control values accepted by the simulator backend." }); } catch (error) { notify({ tone: "error", text: (error as Error).message }); } finally { setPending(false); } };
  const confirmDanger = async () => { if (!danger) return; try { const response = await api.command("EMS", danger.slug, 1); const diagnostic = response.diagnostic; notify({ tone: diagnostic?.code === "accepted_but_unsupported" ? "error" : "success", text: diagnostic?.code === "accepted_but_unsupported" ? `${danger.label} was accepted, but has no modeled physical effect.` : `${danger.label} was accepted by the backend.` }); } catch (error) { notify({ tone: "error", text: (error as Error).message }); } finally { setDanger(null); } };
  return <><div className="page-heading"><div><p className="eyebrow">Confirmed commands only</p><h1>Control</h1><p>Actions are shown as successful only after a backend response.</p></div></div><form onSubmit={send} className="control-grid"><Card title="Operating state"><label>Power<select value={on} onChange={(event) => setOn(event.target.value)}><option value="1">Power On</option><option value="0">Power Off</option></select></label><label>Operating mode<select value={mode} onChange={(event) => setMode(event.target.value)}><option value="0">Manual</option><option value="1">Auto Strategy</option><option value="2">Remote</option></select></label><label>Active power <span>kW</span><input type="number" value={power} onChange={(event) => setPower(event.target.value)} step="1" /></label><label>Reactive power <span>kvar</span><input type="number" value={reactive} onChange={(event) => setReactive(event.target.value)} step="1" /></label><p className="form-hint">Negative active power means charging; positive active power means discharging.</p></Card><Card title="Operating limits"><label>Maximum charge SoC <span>%</span><input type="number" value={maxChargeSOC} onChange={(event) => setMaxChargeSOC(event.target.value)} /></label><label>Minimum discharge SoC <span>%</span><input type="number" value={minDischargeSOC} onChange={(event) => setMinDischargeSOC(event.target.value)} /></label><label>Maximum charge power <span>kW</span><input type="number" value={maxChargePower} onChange={(event) => setMaxChargePower(event.target.value)} /></label><label>Maximum discharge power <span>kW</span><input type="number" value={maxDischargePower} onChange={(event) => setMaxDischargePower(event.target.value)} /></label><button className="button button--primary" disabled={pending}>{pending ? "Sending…" : "Apply controls"}</button></Card><Card title="Current dispatch"><dl className="definition-list"><dt>Requested</dt><dd>{number(point(points, "EMS", "desired_active_power_kw"))} kW</dd><dt>Dispatched</dt><dd>{number(point(points, "EMS", "last_charge_discharge_power_kw"))} kW</dd><dt>Reason</dt><dd>Backend limits are authoritative.</dd></dl></Card><Card title="Danger Zone" className="danger-card"><p>Dangerous commands need confirmation and can still be rejected by backend configuration.</p><div className="button-row"><button type="button" className="button button--danger" onClick={() => setDanger({ slug: "trip", label: "Trip" })}>Trip…</button><button type="button" className="button button--secondary" onClick={() => setDanger({ slug: "clear_protection", label: "Clear Protection" })}>Clear Protection…</button></div></Card></form>{danger && <ConfirmationDialog title={`Confirm ${danger.label}`} detail="This is a dangerous simulator command. The backend may still reject it if dangerous commands are disabled." onCancel={() => setDanger(null)} onConfirm={() => void confirmDanger()} />}</>;
}

function TestLab({ catalog, notify }: ReturnType<typeof useSimulator> & { notify: (toast: Toast) => void }) {
  const [query, setQuery] = useState("cell temperature"); const [protocol, setProtocol] = useState("modbus"); const [mode, setMode] = useState("drop"); const [delay, setDelay] = useState("200"); const [confirmReset, setConfirmReset] = useState(false); const alarms = useMemo(() => catalog.filter((item) => item.class === "alarm" && item.name_raw.toLowerCase().includes(query.toLowerCase())).slice(0, 8), [catalog, query]); const selected = alarms[0];
  const run = async (action: () => Promise<unknown>, success: string) => { try { await action(); notify({ tone: "success", text: success }); } catch (error) { notify({ tone: "error", text: (error as Error).message }); } };
  return <><div className="page-heading"><div><p className="eyebrow">Fault injection and protocol testing</p><h1>Test Lab</h1><p>Alarm severity is not inferred when it is absent from the catalog.</p></div></div><div className="lab-grid"><Card title="Alarm injection"><label>Search alarms<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="alarm-results">{alarms.map((alarm) => <div key={`${alarm.device}/${alarm.slug}`}><div><b>{alarm.device}</b> {alarm.name_raw}</div><div className="button-row"><button className="button button--secondary" onClick={() => void run(() => api.injectFault(alarm.device, alarm.slug, 1), "Alarm injected and confirmed.")}>Inject</button><button className="button button--secondary" onClick={() => void run(() => api.clearFault(alarm.device, alarm.slug), "Alarm cleared and confirmed.")}>Clear</button></div></div>)}{!selected && <p className="empty">No matching alarms.</p>}</div></Card><Card title="Link fault simulation"><label>Protocol<select value={protocol} onChange={(event) => setProtocol(event.target.value)}><option value="iec104">IEC-104</option><option value="modbus">Modbus</option></select></label><label>Mode<select value={mode} onChange={(event) => setMode(event.target.value)}>{["drop", "hang", "delay", "heartbeat_pause"].map((item) => <option key={item}>{item}</option>)}</select></label>{mode === "delay" && <label>Delay <span>ms</span><input type="number" value={delay} onChange={(event) => setDelay(event.target.value)} /></label>}<div className="button-row"><button className="button button--primary" onClick={() => void run(() => api.link(protocol, mode, Number(delay)), "Link fault applied and confirmed.")}>Apply</button><button className="button button--secondary" onClick={() => void run(() => api.clearLink(protocol), "Link restored and confirmed.")}>Restore link</button></div></Card><Card title="Reset simulator"><p>Restores the deterministic startup state and stops active scenarios.</p><button className="button button--danger" onClick={() => setConfirmReset(true)}>Reset…</button></Card></div>{confirmReset && <ConfirmationDialog title="Confirm reset" detail="Reset restores the deterministic startup state and stops active scenarios." onCancel={() => setConfirmReset(false)} onConfirm={() => { setConfirmReset(false); void run(api.reset, "Simulator reset and confirmed."); }} />}</>;
}
