"""Tests for codegen.gen_python against the real catalog: the package must
import cleanly and pass mypy --strict (Task 3 acceptance criteria,
verbatim), plus constant/model counts matching the catalog.
"""
from __future__ import annotations

import importlib
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest

from codegen.gen_python import main as gen_python_main
from tests.conftest import requires_catalog

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "catalog" / "point_catalog.json"
PY_PKG = REPO_ROOT / "gen" / "python" / "m261_points"

# Checked as an importable module of the *running* interpreter (mypy is
# always invoked as `sys.executable -m mypy` below), not shutil.which,
# which only sees console scripts on $PATH — misses a venv's mypy unless
# the venv happens to be "activated" in the calling shell.
pytestmark = [
    pytest.mark.skipif(importlib.util.find_spec("mypy") is None, reason="mypy not installed"),
    requires_catalog,
]


@pytest.fixture(scope="module", autouse=True)
def generated():
    gen_python_main([])


@pytest.fixture(scope="module")
def m261_points_module():
    sys.path.insert(0, str(REPO_ROOT / "gen" / "python"))
    try:
        import m261_points

        importlib.reload(m261_points)
        yield m261_points
    finally:
        sys.path.remove(str(REPO_ROOT / "gen" / "python"))


def test_package_imports(m261_points_module):
    records = json.loads(CATALOG.read_text(encoding="utf-8"))
    assert len(m261_points_module.POINTS) == len(records)


def test_mypy_strict_clean():
    result = subprocess.run(
        [sys.executable, "-m", "mypy", str(PY_PKG), "--strict"],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_constant_count_matches_catalog():
    records = json.loads(CATALOG.read_text(encoding="utf-8"))
    src = (PY_PKG / "constants.py").read_text(encoding="utf-8")
    import re

    const_lines = re.findall(r"^(\w+): int = \d+", src, re.MULTILINE)
    iec_consts = [name for name in const_lines if not name.endswith("_MODBUS")]
    assert len(iec_consts) == len(records)


def test_generated_files_start_with_do_not_edit_banner():
    for name in ("constants.py", "enums.py", "models.py", "points.py", "__init__.py"):
        text = (PY_PKG / name).read_text(encoding="utf-8")
        assert text.startswith("# Code generated by codegen/gen_python.py"), name
        assert "DO NOT EDIT" in text.splitlines()[0]


def test_point_meta_round_trips_key_fields(m261_points_module):
    records = {(r["device"], r["slug"]): r for r in json.loads(CATALOG.read_text(encoding="utf-8"))}
    for key, meta in m261_points_module.POINTS.items():
        rec = records[(key.device, key.slug)]
        assert meta.iec104_addr == rec["iec104_addr"]
        assert meta.modbus_addr == rec["modbus_addr"]
        assert meta.name_raw == rec["name_raw"]
        assert meta.dangerous == rec["dangerous"]
