"""Tests for codegen.gen_go against the real catalog. Exercises the actual
Go toolchain (build/vet/test) rather than just checking the generated
source text — this is what the Task 3 acceptance criteria ask for
verbatim ("go build ./... and go vet ./... pass").
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest

from codegen.gen_go import main as gen_go_main

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "catalog" / "point_catalog.json"
GO_PKG = REPO_ROOT / "gen" / "go" / "m261points"

pytestmark = pytest.mark.skipif(shutil.which("go") is None, reason="Go toolchain not installed")


@pytest.fixture(scope="module", autouse=True)
def generated():
    gen_go_main([])


def test_go_build_succeeds():
    result = subprocess.run(["go", "build", "./..."], cwd=REPO_ROOT, capture_output=True, text=True)
    assert result.returncode == 0, result.stderr


def test_go_vet_succeeds():
    result = subprocess.run(["go", "vet", "./..."], cwd=REPO_ROOT, capture_output=True, text=True)
    assert result.returncode == 0, result.stderr


def test_go_test_succeeds():
    """This runs the generated codec_test.go — the round-trip test itself
    (decode/encode of every data type returns the original value)."""
    result = subprocess.run(
        ["go", "test", "./gen/go/m261points/..."], cwd=REPO_ROOT, capture_output=True, text=True
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_generated_go_is_gofmt_clean():
    result = subprocess.run(["gofmt", "-l", str(GO_PKG)], capture_output=True, text=True)
    assert result.stdout.strip() == "", f"not gofmt-clean: {result.stdout}"


def test_constant_count_matches_catalog():
    """Acceptance: 'number of constants matches number of points in the
    catalog' — one IEC-104 address constant per point, always; Modbus
    constants are extra (only for points that have one), so the count of
    IEC-104 constants specifically must equal len(catalog)."""
    records = json.loads(CATALOG.read_text(encoding="utf-8"))
    src = (GO_PKG / "constants.go").read_text(encoding="utf-8")
    # Every constant line looks like "Ident = N" or "Ident = N // comment";
    # the Modbus ones are named "...Modbus" — count everything else.
    const_lines = re.findall(r"^\t(\w+)\s*=\s*\d+", src, re.MULTILINE)
    iec_consts = [name for name in const_lines if not name.endswith("Modbus")]
    assert len(iec_consts) == len(records)


def test_points_map_has_one_entry_per_catalog_record():
    records = json.loads(CATALOG.read_text(encoding="utf-8"))
    src = (GO_PKG / "points.go").read_text(encoding="utf-8")
    assert src.count("PointKey{Device:") == len(records)


def test_generated_files_start_with_do_not_edit_banner():
    for name in ("codec.go", "constants.go", "enums.go", "points.go", "state.go"):
        text = (GO_PKG / name).read_text(encoding="utf-8")
        assert text.startswith("// Code generated by codegen/gen_go.py"), name
        assert "DO NOT EDIT" in text.splitlines()[0]
