"""Shared helpers for the codegen scripts (gen_go.py, gen_python.py,
gen_seeds.py). Not generated code itself — this is the generator's own
support module.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CATALOG = REPO_ROOT / "catalog" / "point_catalog.json"

GENERATED_BANNER_GO = (
    "// Code generated by codegen/gen_go.py from catalog/point_catalog.json. DO NOT EDIT."
)
GENERATED_BANNER_PY = (
    "# Code generated by codegen/gen_python.py from catalog/point_catalog.json. DO NOT EDIT."
)
GENERATED_BANNER_JSON_NOTE = (
    "Generated by codegen/gen_seeds.py from catalog/point_catalog.json. DO NOT EDIT."
)

# Device codes (§4.1) -> identifier-safe PascalCase, used as a prefix for
# every generated constant/type/field for that device.
DEVICE_PASCAL: dict[str, str] = {
    "EMS": "EMS",
    "PCS": "PCS",
    "BMS": "BMS",
    "BMS_CELLS": "BMSCells",
    "PCS_METER": "PCSMeter",
    "DIDO": "DIDO",
    "TMS": "TMS",
    "CSJ": "CSJ",
}

DEVICE_ORDER = ["EMS", "PCS", "BMS", "BMS_CELLS", "TMS", "PCS_METER", "DIDO", "CSJ"]


def load_catalog(path: Path = DEFAULT_CATALOG) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


def group_by_device(records: list[dict]) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {d: [] for d in DEVICE_ORDER}
    for r in records:
        out.setdefault(r["device"], []).append(r)
    return out


_WORD_RE = re.compile(r"[a-zA-Z0-9]+")


def slug_to_pascal(slug: str) -> str:
    """'set_active_power' -> 'SetActivePower'. Never starts with a digit —
    Go/Python identifiers can't, so a leading numeral gets an 'N' prefix
    (e.g. the two '24V ...'/'15V ...' fault names on PCS)."""
    parts = _WORD_RE.findall(slug)
    pascal = "".join(p[:1].upper() + p[1:] for p in parts)
    if pascal and pascal[0].isdigit():
        pascal = "N" + pascal
    return pascal or "Point"


def point_identifier(device: str, slug: str) -> str:
    """The full, package-unique identifier for a point: device prefix +
    PascalCase slug, e.g. EMS/set_active_power -> 'EMSSetActivePower'."""
    return DEVICE_PASCAL[device] + slug_to_pascal(slug)


def enum_items(enum: dict[str, str] | None) -> list[tuple[int, str]]:
    """Catalog enums are {"0": "Manual", "1": "Auto Strategy", ...}; return
    them as (code, label) pairs sorted by code, codes coerced to int (the
    catalog schema doesn't rule out negative codes, though none appear in
    the current map)."""
    if not enum:
        return []
    return sorted(((int(k), v) for k, v in enum.items()), key=lambda kv: kv[0])
