#!/usr/bin/env python3
"""Generate docs/point-reference.md from catalog/point_catalog.json —
Task 8 item 4: a generated, human-readable reference of every point in
the catalog (all 1513 records — Task 8's own acceptance criterion).

Usage:
    python3 -m codegen.gen_docs
    python3 -m codegen.gen_docs --catalog catalog/point_catalog.json --out docs/point-reference.md
"""
from __future__ import annotations

import argparse
from pathlib import Path

from codegen.common import DEVICE_ORDER, REPO_ROOT, enum_items, group_by_device, load_catalog

DEFAULT_OUT = REPO_ROOT / "docs" / "point-reference.md"

GENERATED_BANNER_MD = (
    "Generated by `codegen/gen_docs.py` from `catalog/point_catalog.json`. DO NOT EDIT."
)

# §2.2: the Modbus function(s) each register class is read/written with —
# purely descriptive here, mirrors modbustcp's own classBase table.
_MODBUS_CLASS_LABEL = {2: "discrete input", 3: "holding", 4: "input"}


def _md_escape(s: str) -> str:
    """Escapes the handful of characters that would otherwise break a
    Markdown table cell or get misread as formatting — a table cell is
    one line, so '|' and literal newlines are the two that actually
    matter here."""
    return s.replace("|", "\\|").replace("\n", " ").replace("\r", "")


def _cell(v) -> str:
    if v is None:
        return "—"
    return _md_escape(str(v))


def _modbus_cell(r: dict) -> str:
    if r["modbus_addr"] is None:
        return "—"
    label = _MODBUS_CLASS_LABEL.get(r["modbus_class"], f"class {r['modbus_class']}")
    funcs = r.get("modbus_function") or []
    fc = "/".join(f"FC{f:02d}" for f in funcs) if funcs else "?"
    return f"{r['modbus_addr']} ({fc}, {label})"


def _enum_cell(r: dict) -> str:
    items = enum_items(r.get("enum"))
    if not items:
        return "—"
    return _md_escape("; ".join(f"{code}={label}" for code, label in items))


def _range_cell(r: dict) -> str:
    rng = r.get("range")
    if not rng:
        return "—"
    lo = rng.get("min")
    hi = rng.get("max")
    return _md_escape(f"[{lo if lo is not None else '—'}, {hi if hi is not None else '—'}]")


def _device_summary(records: list[dict]) -> str:
    alarm = sum(1 for r in records if r["class"] == "alarm")
    telemetry = sum(1 for r in records if r["class"] == "telemetry")
    setpoint = sum(1 for r in records if r["class"] == "setpoint")
    return f"{len(records)} points: {alarm} alarm, {telemetry} telemetry, {setpoint} setpoint"


def render(records: list[dict]) -> str:
    by_device = group_by_device(records)

    lines = ["# ENERGRID M261 Point Reference", ""]
    lines.append(GENERATED_BANNER_MD)
    lines.append("")
    lines.append(
        f"**{len(records)} points** across {sum(1 for d in DEVICE_ORDER if by_device[d])} devices. "
        "Every write-capable point is a `setpoint`; every other point is read-only "
        "(`alarm` or `telemetry`) as seen by both protocols. `IEC-104` and `Modbus` "
        "are the addresses a client actually uses; `Readback IEC-104` (setpoints "
        "only) is the read-only mirror the same value shows up at after a write — "
        "see the simulator's own point catalog for the authoritative machine-"
        "readable form (`catalog/point_catalog.json`, private/internal)."
    )
    lines.append("")

    lines.append("## Devices")
    lines.append("")
    for device in DEVICE_ORDER:
        recs = by_device[device]
        if not recs:
            continue
        lines.append(f"- [{device}](#{device.lower().replace('_', '')}) — {_device_summary(recs)}")
    lines.append("")

    for device in DEVICE_ORDER:
        recs = by_device[device]
        if not recs:
            continue
        recs = sorted(recs, key=lambda r: (r["iec104_addr"] if r["iec104_addr"] is not None else -1))

        lines.append(f"## {device}")
        lines.append("")
        lines.append(_device_summary(recs))
        lines.append("")
        lines.append("| Slug | Name | Class | Access | IEC-104 | Readback IEC-104 | Modbus | Type | Scale | Unit | Enum | Range | Dangerous |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for r in recs:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{r['slug']}`",
                        _cell(r["name_raw"]),
                        _cell(r["class"]),
                        _cell(r["access"]),
                        _cell(r["iec104_addr"]),
                        _cell(r["readback_iec104_addr"]),
                        _modbus_cell(r),
                        _cell(r["data_type"]),
                        _cell(r["scale"]),
                        _cell(r["unit"]),
                        _enum_cell(r),
                        _range_cell(r),
                        "yes" if r["dangerous"] else "no",
                    ]
                )
                + " |"
            )
        lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--catalog", type=Path, default=None)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args(argv)

    records = load_catalog(args.catalog) if args.catalog else load_catalog()
    doc = render(records)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(doc, encoding="utf-8")
    print(f"wrote {args.out} ({len(records)} points)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
